### ISSUE TITLE
Error with versions of NDM and NODE

### ISSUE THREAD

**Issue by Ricardo-Developer** [720kb/ndm#247]
## Issue Report
I have _ndm_, _node_ and _npm_ installed version on stable releases as below, and still when I run doctor is shows different versions.
What seems to be the problem and how to fix it?

Thank you!

#### REQUIRED 
OS / OS version: **MacOS 10.13.3**

ndm version: **1.2.0**
 
node version: **9.6.1**

npm version: **5.7.1**

node installed via (brew, n, nvm, pkg, other ...): **n**

#### OPTIONAL 

$ which node: **/usr/local/bin/node**

$ which npm: **/usr/local/bin/npm**

#### IMPORTANT

**npm doctor**
npm WARN verifyCachedFiles Content garbage-collected: 443 (10333722 bytes)
npm WARN verifyCachedFiles Cache issues have been fixed
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.7.1
node -v                             v9.6.1
npm config get registry             https://registry.npmjs.org/
which git                           /usr/local/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2713 tarballs

#### APPRECIATED

**Console Log App:**
angular.js:14525 Storage: OK
angular.js:14525 DOM is ready
angular.js:14525 DOM is ready for npm
index.js:formatted:1858Unable to read project path: Error: ENOENT: no such file or directory, lstat '/Users/**_myUserName_**/Downloads/devportfolio-master'
(anonymous) @ index.js:formatted:1858
angular.js:14525 npm is ready
angular.js:14525 Global is enabled
angular.js:14525 Object
angular.js:14525 Object
angular.js:14525 Selected project payload Object
angular.js:14525 Platform darwin
angular.js:14525 Object
angular.js:14525 stdout: {}

index.js:formatted:435Uncaught (in promise) TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at file:///Applications/ndm.app/Contents/Resources/app/dist/js/index.js:1:9339
    at process._tickCallback (internal/process/next_tick.js:103:7)
angular.js:14525End of command ping
angular.js:14525child process exited with code 0
angular.js:14525End of command outdated
angular.js:14525child process exited with code 0
angular.js:14525End of command listOutdated
angular.js:14525child process exited with code 0

#### THE PROBLEM
When I run doctor in CLI it's ok, when I run it in the App it gives errors in the versions of npm and node to use latests.
![ndm](https://user-images.githubusercontent.com/30289997/36935036-e9a2b742-1ee9-11e8-936a-8f59b23ee7f6.png)

![terminal](https://user-images.githubusercontent.com/30289997/36935040-00832a14-1eea-11e8-8705-3c5161da7513.png)

#### REPRODUCE THE PROBLEM
Run doctor in the app

**Comment by ToraTengu** [comment]
Same thing with my win7 x64 install.
I had node and npm outdated, installed the latest msi from nodejs, restarted ndm (nice piece of software by the way) , ran the doctor and it stills warns me about oudated versions of node and npm!

**Comment by martinleopold** [comment]
Same here on Mac OS 10.13.5, ndm 1.20
![screen shot 2018-07-03 at 09 09 54](https://user-images.githubusercontent.com/1692826/42204280-89122472-7ea1-11e8-8c04-107e85591d7e.png)
<img width="762" alt="screen shot 2018-07-03 at 09 10 26" src="https://user-images.githubusercontent.com/1692826/42204284-8b44c948-7ea1-11e8-9e69-7438c60a9263.png">
